/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服务与数据库连通探测(ADR-A-003:进程存活恒 200)
         * @description ADR-A-003:服务进程存活即 HTTP 200;数据库状态由 data.db 表达(ok|error)。
         */
        get: operations["health_handler_alias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服务与数据库连通探测(ADR-A-003:进程存活恒 200)
         * @description ADR-A-003:服务进程存活即 HTTP 200;数据库状态由 data.db 表达(ok|error)。
         */
        get: operations["health_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 统一响应信封。
         *
         *     成功:`{ "success": true, "data": {...}, "errorCode": null, "message": null }`
         *     失败:`{ "success": false, "data": null, "errorCode": "...", "message": "..." }`
         */
        Envelope_HealthData: {
            /** @description 健康数据(RULE-001 白名单:恰好三个字段,不含连接串/主机名/内部路径)。 */
            data?: {
                /** @description "ok" | "error" — 数据库可用性 */
                db: string;
                /** @description 恒 "ok" — 服务进程存活即可应答(ADR-A-003) */
                status: string;
                /** @description 后端版本号 */
                version: string;
            };
            errorCode?: null | components["schemas"]["ErrorCode"];
            message?: string | null;
            success: boolean;
        };
        /**
         * @description 集中错误码表(arch 基线 §6.2)。A 期实际可能出现的仅 INTERNAL_ERROR;
         *     其余码随各期业务引入,RULE-003 要求 errorCode 只能取自本枚举。
         *     wire 格式为 SCREAMING_SNAKE(前端按字符串映射文案),故保留全大写命名。
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL_ERROR";
        /** @description 健康数据(RULE-001 白名单:恰好三个字段,不含连接串/主机名/内部路径)。 */
        HealthData: {
            /** @description "ok" | "error" — 数据库可用性 */
            db: string;
            /** @description 恒 "ok" — 服务进程存活即可应答(ADR-A-003) */
            status: string;
            /** @description 后端版本号 */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_handler_alias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 统一信封;data.db=ok|error 表达数据库状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthData"];
                };
            };
        };
    };
    health_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 统一信封;data.db=ok|error 表达数据库状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthData"];
                };
            };
        };
    };
}
